### ISSUE TITLE
[BC] Type conflict with Laravel

### ISSUE THREAD

**Issue by mathieutu** [tighten/collect#90]
Hi again!
I'm sorry to be the one who open all theses issues, but as I'm working a lot with collect and Laravel for now, I'm seeing all the problems.

Again a problem due to the namespace change (and so, the composer replace) but not the fault of composer this time:

I have a regression in my project because of a `Tightenco\Collect\Support\Collection::make`

In fact you can reproduce easily the problem in a Laravel project:

```php
$items = User::all();
Tightenco\Collect\Support\Collection::make($items);
```

The function that converts $items is this one: 
```php
 protected function getArrayableItems($items)
    {
        if (is_array($items)) {
            return $items;
        } elseif ($items instanceof self) {
            return $items->all();
        } elseif ($items instanceof Arrayable) {
            return $items->toArray();
        } elseif ($items instanceof Jsonable) {
            return json_decode($items->toJson(), true);
        } elseif ($items instanceof JsonSerializable) {
            return $items->jsonSerialize();
        } elseif ($items instanceof Traversable) {
            return iterator_to_array($items);
        }

        return (array) $items;
    }
``` 

Previously, when collect was replaced by Laravel Collections, the return value was
```php
            return $items->all();
```
because `$this`and `$items` was from the same class.

Now, because they are from different classes the value will be 
```php
            return $items->toArray();
```

**which is not the same at all** and breaks totally my package, and my project! 😅 

I don't have right now a simple solution, but I definitely think that changing the package namespace was much more complicated than we thought.. 😕

Maybe, you or @adamwathan (as he uses it too in his packages, and so will have the same problems) should discuss with Taylor about a more global solution (extract definitely the collections from Laravel for example).

Thank's for your work, I'll hope we will find a solution to keep using this cool package.

**Comment by mattstauffer** [comment]
@mathieutu Thanks for taking a look at this! Very good point. I'm curious about how we can modify it to fix this `self` reference.  And you're right--this was more complicated than we had hoped. Fixed some problems, caused more.

**Comment by mattstauffer** [comment]
Our current best idea is to programmatically replace all the `instanceof self` checks, which is a bit of a hack but we're out of better ideas. Anyone else have any other ideas?

**Comment by antonioribeiro** [comment]
Another one is to be a little more explicit by renaming

```
Tightenco\Collect\Support\Collection;
```

to

```
use Tightenco\Collect\Support\IlluminateCollection;
```

And extending it:

```
<?php

namespace Tightenco\Collect\Support;

use Tightenco\Collect\Support\IlluminateCollection;

class Collection extends IlluminateCollection
{
    /**
     * Results array of items from Collection or Arrayable.
     *
     * @param  mixed  $items
     * @return array
     */
    protected function getArrayableItems($items)
    {
        if (is_array($items)) {
            return $items;
        } elseif ($items instanceof self || $items instanceof Illuminate\Support\Collection) {
            return $items->all();
        } elseif ($items instanceof Arrayable) {
            return $items->toArray();
        } elseif ($items instanceof Jsonable) {
            return json_decode($items->toJson(), true);
        } elseif ($items instanceof JsonSerializable) {
            return $items->jsonSerialize();
        } elseif ($items instanceof Traversable) {
            return iterator_to_array($items);
        }

        return (array) $items;
    }
}
```

**Comment by antonioribeiro** [comment]
An alternative to not tie it to Illuminate directly, being a little more generic, but also riskier:

``` php
 if ($items instanceof self || (is_object($items) && method_exists($items, 'all'))) {
    return $items->all();
}
```

**Comment by mathieutu** [comment]
Hi guys!
Some news about that?

@mattstauffer @adamwathan Do you think we could convince @taylorotwell to definitely create a Illuminate/Collection to avoid all of theses problems?

I like your ideas @antonioribeiro but, this is not the only place where an `instance of self` is and will be done, so they are not durable fixes in my opinion.

**Comment by mattstauffer** [comment]
@mathieutu Taylor was always on-board with separating it, but because it has so many dependencies on other things in Support, it was always a really big task that would have negative impacts on the rest of the framework.

It's possible that things are simpler now; or the work we've done to make it clear what Collect relies on would make it an easier task. But it's not that he wasn't willing; it's that we tried it and it had a negative impact on the framework

With regard to the `self` check, I would love for someone to audit the code and to see what would happen were we to replace all instances of `$items instanceof self` with `$items instanceof self || $items instanceof Illuminate\Support\Collection` like @antonioribeiro suggested.

**Comment by mathieutu** [comment]
Hi guys, I spent hours on an issue today before finding that this was exactly this one... 😞 

We need to do something durable for that.

And @mattstauffer I'm affraid that the solution you proposed isn't one available, because we will have exactly the same problem with a Support/Collection of Tightenco/Collections. A `self` in support one will not resolve tightenco ones...

Maybe could we dynamically extends the Support collection (don't know how for now, I have some ideas but I have to make some tests). But we have to do that for all the files (including Arayable and other interfaces).

Will you guys be at the Laracon EU? I'll try to discuss about that with @adamwathan and @taylorotwell to find a solution, but with my english spoken level, I think I will not success to explain the problem.

If needed I really can make a PR to make an illuminate/collection package (which will be quite a copy of tightenco), but only if taylor will accept it...

**Comment by mattstauffer** [comment]
@mathieutu I will not be there, but I look forward to being a part of any/all solutions we can come up with. :)

**Comment by mathieutu** [comment]
@mattstauffer Here we go. I've taked with @taylorotwell and [the PR](https://github.com/laravel/framework/pull/25421) is in the launch pad! I've made things a bit different than in the package (especially because of non existing thing anymore, or testing), so please feel free to make any comments!
